spring.application.name=KittFinder

spring.datasource.url=jdbc:mysql://mysql-21c7c324-vg3772285-d689.d.aivencloud.com:24659/defaultdb?allowPublicKeyRetrieval=true&useSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_g0QN-6XpE4TspQ8AMmT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
