spring.application.name=KittFinder

spring.datasource.url=jdbc:mysql://mysql-21c7c324-vg3772285-d689.d.aivencloud.com:24659/defaultdb?allowPublicKeyRetrieval=true&useSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_g0QN-6XpE4TspQ8AMmT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Cloudinary Configuration
cloudinary.cloud-name=di2xa1evz
cloudinary.api-key=878998562368755
cloudinary.api-secret=00gv7eHgp1Uas5ZSC7F6Nvw8yh8

# File upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB